services:
  - type: web
    name: healix-medicare
    runtime: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/doctor-appointment-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
      - key: PORT
        value: 8082
    healthCheckPath: /
